# Generated by Django 3.2.5 on 2021-07-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=250)),
                ('userid', models.CharField(max_length=250)),
                ('profilename', models.CharField(max_length=250)),
                ('helpfulness', models.CharField(max_length=250)),
                ('score', models.FloatField()),
                ('summary', models.TextField()),
                ('time', models.TimeField()),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prueba',
                'managed': False,
            },
        ),
    ]
